# application config
spring:
  application:
    name: banyan
  datasource:
    url: jdbc:mysql://localhost:3306/allspark?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

cli:
  mybatis:
    outputPath: banyan-generator/build/tmp/mybatis
    modelName: demo
    author: dingchengfeng