server:
  port: 10000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: BanyanAdmin

management:
  endpoint:
    health:
      show-details: always
