banyan:
  app:
    tmpdir: ${app.tmpdir:tmp}
    logdir: ${app.logdir:log}
    component:
      host: ${app.component.host:localhost}

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
  charset:
    console: UTF-8
    file: UTF-8
  config: classpath:logback/logback.xml
  file:
    path: ${banyan.app.logdir}
    name: ${banyan.app.logdir}/bootstrap.log

spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource:
    url: jdbc:mysql://${banyan.app.component.host}:3306/banyan?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # Flyway
  ## 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
  flyway:
    enabled: true
    out-of-order: true
    baseline-on-migrate: true
    validate-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://${banyan.app.component.host}:3306/banyan?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true
    user: root
    password: root
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-host-type: ip
        url: http://localhost:10000
  file-storage:
    default-platform: minio-1
    thumbnail-suffix: ".min.jpg"
    minio:
      - platform: minio-1
        enable-storage: true
        access-key: minio
        secret-key: minio1234
        bucket-name: allspark
        end-point: http://${banyan.app.component.host}:9000/

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: null
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /doc/openapi.json
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    logfile:
      enabled: true
      external-file: ${banyan.app.logdir}/bootstrap.log
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
      mode: full